# coding: utf-8

"""
    Vorboss Product Availability API

    This API is provided by Vorboss to allow customers to check which products are available at a given postcode.  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ProductAvailability
from ProductAvailability.ProductAvailability.postcode import Postcode  # noqa: E501
from ProductAvailability.rest import ApiException


class TestPostcode(unittest.TestCase):
    """Postcode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostcode(self):
        """Test Postcode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProductAvailability.models.postcode.Postcode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
