# coding: utf-8

"""
    Vorboss Product Availability API

    This API is provided by Vorboss to allow customers to check which products are available at a given postcode.  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ProductAvailability
from ProductAvailability.ProductAvailability.postcode_available_products import PostcodeAvailableProducts  # noqa: E501
from ProductAvailability.rest import ApiException


class TestPostcodeAvailableProducts(unittest.TestCase):
    """PostcodeAvailableProducts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostcodeAvailableProducts(self):
        """Test PostcodeAvailableProducts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProductAvailability.models.postcode_available_products.PostcodeAvailableProducts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
