# coding: utf-8

"""
    Vorboss Product Availability API

    This API is provided by Vorboss to allow customers to check which products are available at a given postcode.  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ProductAvailability
from ProductAvailability.ProductAvailability.product_availability_api import ProductAvailabilityApi  # noqa: E501
from ProductAvailability.rest import ApiException


class TestProductAvailabilityApi(unittest.TestCase):
    """ProductAvailabilityApi unit test stubs"""

    def setUp(self):
        self.api = ProductAvailabilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_confirm_postcode(self):
        """Test case for confirm_postcode

        Check a postcode  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
