# coding: utf-8

"""
    Vorboss Product Availability API

    This API is provided by Vorboss to allow customers to check which products are available at a given postcode.  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Postcode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'message': 'str',
        'postcode': 'str',
        'available_products': 'list[PostcodeAvailableProducts]'
    }

    attribute_map = {
        'id': 'id',
        'message': 'message',
        'postcode': 'postcode',
        'available_products': 'availableProducts'
    }

    def __init__(self, id=None, message=None, postcode=None, available_products=None):  # noqa: E501
        """Postcode - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._message = None
        self._postcode = None
        self._available_products = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if message is not None:
            self.message = message
        if postcode is not None:
            self.postcode = postcode
        if available_products is not None:
            self.available_products = available_products

    @property
    def id(self):
        """Gets the id of this Postcode.  # noqa: E501


        :return: The id of this Postcode.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Postcode.


        :param id: The id of this Postcode.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def message(self):
        """Gets the message of this Postcode.  # noqa: E501


        :return: The message of this Postcode.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Postcode.


        :param message: The message of this Postcode.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def postcode(self):
        """Gets the postcode of this Postcode.  # noqa: E501


        :return: The postcode of this Postcode.  # noqa: E501
        :rtype: str
        """
        return self._postcode

    @postcode.setter
    def postcode(self, postcode):
        """Sets the postcode of this Postcode.


        :param postcode: The postcode of this Postcode.  # noqa: E501
        :type: str
        """

        self._postcode = postcode

    @property
    def available_products(self):
        """Gets the available_products of this Postcode.  # noqa: E501


        :return: The available_products of this Postcode.  # noqa: E501
        :rtype: list[PostcodeAvailableProducts]
        """
        return self._available_products

    @available_products.setter
    def available_products(self, available_products):
        """Sets the available_products of this Postcode.


        :param available_products: The available_products of this Postcode.  # noqa: E501
        :type: list[PostcodeAvailableProducts]
        """

        self._available_products = available_products

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Postcode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Postcode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
